Repository govind-kumarr/simple_rag_dashboard, pull requests merged in 2024-05, with the labels that each got.

#57 #12 Implement email verfication
  chatbot_rjs/src/components/Sidebar.jsx
  chatbot_rjs/src/pages/EmailVerification.jsx
  node_server/.env.example
  node_server/controller/auth.controller.js
  node_server/package-lock.json
  node_server/package.json
  node_server/routes/auth.routes.js
  node_server/server.js
  node_server/utils/VerfiyEmail.js
Labels: gssoc, level2

#62 myprofile_frontend
  chatbot_rjs/src/pages/MyProfile.jsx
Labels: gssoc, level2

#63 Profile
  chatbot_rjs/src/pages/MyProfile.jsx
  node_server/controller/auth.controller.js
  node_server/models/User.model.js
  node_server/routes/auth.routes.js
Labels: gssoc, level1

#70 lambda code updated
  node_server/handler.py
Labels: gssoc, level3

#66 trainAI page UI
  chatbot_rjs/src/pages/MyProfile.jsx
  chatbot_rjs/src/pages/TrainAi.jsx
  chatbot_rjs/src/routes/AllRoutes.jsx
Labels: gssoc, level2

#84 Updated doc for mitigation of cold start
  node_server/Documentation_coldstart_mitigation
Labels: gssoc, level1

#80 [FEAT]: Created Issue forms and made the issue options more visually appealing
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/documentation_update.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: gssoc, level1
